AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "gems/*/vendor/**/*"
    - "gems/*/bin/**/*"

# spec はブロックが構造上長くなるため BlockLength の対象外にする。
Metrics/BlockLength:
  Exclude:
    - "gems/*/spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
